# BitcoinAll LIVE (main) — Node 2 Validator + wallet
server=1
minrelaytxfee=0.01
incrementalrelayfee=0.01
blockmintxfee=0.01
fallbackfee=0.01
maxtxfee=100
txindex=1
rpcuser=btca-live
rpcpassword=BtcaLive-Demo-9333!
discover=0
listenonion=0
dnsseed=0
fixedseeds=0

[main]
port=9334
bind=127.0.0.1
rpcport=8333
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
addnode=127.0.0.1:9333
